### ISSUE TITLE
Error during preinstall

### ISSUE THREAD

**Issue by gitonthescene** [kparc/k#23]
I keep erroring out after accepting the license on osX 12.0.1 (Monterey).  I'm no npm expert, but I can't figure out how to get more information out of what's happening even after googling around.  I guess I'd like to have npm run the build not in silent mode.

```
82 verbose stack Error: @kparc/k@2.0.70 preinstall: `npm run build --silent`
82 verbose stack Exit status 1
82 verbose stack     at EventEmitter.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
82 verbose stack     at EventEmitter.emit (node:events:390:28)
82 verbose stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
82 verbose stack     at ChildProcess.emit (node:events:390:28)
82 verbose stack     at maybeClose (node:internal/child_process:1064:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
83 verbose pkgid @kparc/k@2.0.70
84 verbose cwd /Users/XXXX/bin
85 verbose Darwin 21.1.0
86 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "i" "@kparc/k"
87 verbose node v16.13.1
88 verbose npm  v6.14.15
89 error code ELIFECYCLE
90 error errno 1
91 error @kparc/k@2.0.70 preinstall: `npm run build --silent`
91 error Exit status 1
92 error Failed at the @kparc/k@2.0.70 preinstall script.
92 error This is probably not a problem with npm. There is likely additional logging output above.
93 verbose exit [ 1, true ]
```

There's not a lot more useful that I can spot in the log.  This probably:

```
74 silly lifecycle @kparc/k@2.0.70~preinstall: Returned: code: 1  signal: null
75 info lifecycle @kparc/k@2.0.70~preinstall: Failed to exec preinstall script
```

**Comment by gitonthescene** [comment]
I used `npm pack @kparc/k` to download the tarball to try to run the script by hand and here is the log: [screenlog.0.txt](https://github.com/kparc/k/files/7834497/screenlog.0.txt).  It looks like the download did happen and I do have access to the binary here, but when run with `npm install` it cleans up after the failed preinstall step.  The error seems to be this:

```
+ chmod +x bin/k
+ echo .z.a
+ bin/k
.z.a
    ^
!parse
```
which it seems is looking for the IP address.  Is that right?  Why does it look like a parse error?
