### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by k-olya** [kparc/k#5]
with disabled network:

```
$ node get.js eula
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND shakti.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:410:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'shakti.com'
}
```

let's make sure the users don't see this

# TODO
* [x] ...

**Comment by k-olya** [comment]
solved in #15
